export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE"
    
}

export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE"
}

export const addDATAConstants = {
    ADD_DATA_REQUEST: "ADD_DATA_REQUEST",
    ADD_DATA_SUCCESS: "ADD_DATA_SUCCESS",
    ADD_DATA_FAILURE: "ADD_DATA_FAILURE"
}

export const connectNodeConstants = {
    CONNECT_NODES_REQUEST : "CONNECT_NODES_REQUEST",
    CONNECT_NODES_SUCCESS : "CONNECT_NODES_SUCCESS",
    CONNECT_NODES_FAILURE : "CONNECT_NODES_FAILURE"

}

export const mineBlockConstants = {
    MINE_BLOCK_REQUEST: "MINE_BLOCK_REQUEST",
    MINE_BLOCK_SUCCESS: "MINE_BLOCK_SUCCESS",
    MINE_BLOCK_FAILURE: "MINE_BLOCK_FAILURE"

}

export const replaceChainConstants = {
    REPLACE_CHAIN_REQUEST: "REPLACE_CHAIN_REQUEST",
    REPLACE_CHAIN_SUCCESS: "REPLACE_CHAIN_SUCCESS",
    REPLACE_CHAIN_FAILURE: "REPLACE_CHAIN_FAILURE"

}

export const getCreditConstants = {
    GET_CREDIT_REQUEST: "GET_CREDIT_REQUEST",
    GET_CREDIT_SUCCESS: "GET_CREDIT_SUCCESS",
    GET_CREDIT_FAILURE: "GET_CREDIT_FAILURE"
    
}

export const getOrgTransConstants = {
    GET_ORGTRANS_REQUEST: "GET_ORGTRANS_REQUEST",
    GET_ORGTRANS_SUCCESS: "GET_ORGTRANS_SUCCESS",
    GET_ORGTRANS_FAILURE: "GET_ORGTRANS_FAILURE"
}