export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE"
}

export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE"
}

export const connectNodeConstants = {
    CONNECT_NODES_REQUEST : "CONNECT_NODES_REQUEST",
    CONNECT_NODES_SUCCESS : "CONNECT_NODES_SUCCESS",
    CONNECT_NODES_FAILURE : "CONNECT_NODES_FAILURE"

}

export const replaceChainConstants = {
    REPLACE_CHAIN_REQUEST: "REPLACE_CHAIN_REQUEST",
    REPLACE_CHAIN_SUCCESS: "REPLACE_CHAIN_SUCCESS",
    REPLACE_CHAIN_FAILURE: "REPLACE_CHAIN_FAILURE"

}

export const searchOrgConstants = {
    SEARCH_ORG_REQUEST: "SEARCH_ORG_REQUEST",
    SEARCH_ORG_SUCCESS: "SEARCH_ORG_SUCCESS",
    SEARCH_ORG_FAILURE: "SEARCH_ORG_FAILURE"
}